spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/doulsab/microservice-configserverone.git
          clone-on-start: true
          # default-label: main
          # search-paths:
          #   - configs
server:
  port: 8085
