server:
  port: 8081
# Db configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false&serverTimezone=UTC
    username: doulsab
    password: Doul@#$123
    hikari:
      pool-name: HikariPool-1
      maximum-pool-size: 10
      minimum-idle: 5  # minimum idle connections for the pool if needed
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: User-Service
#This is eureka client configurations
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka