server:
  port: 8083
#  error:
#    include-message: always  # This property ensures that the exception message is included in the response body in UI or Postman, even when the user doesn't use @RestControllerAdvice.
spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://doulsab0786:Daval111@cluster0.cacsbx1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: micro-service
      port: 27017
  config:
    import: optional:configserver://localhost:8085
#This is eureka client configurations
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

