server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb+srv://coder_doulsab:ZccOHuM9svyrIX4z@cluster-dd.eiaow.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-dd
      database: micro-service
      port: 27017
  application:
    name: Rating-Service
#This is eureka client configurations
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka